import os
import shutil
import subprocess
import tempfile

from problems import LaTeXPiece


class TexDocument(LaTeXPiece):
    def __init__(self):
        super().__init__()
        self._doc_class = "\\document""class{article}\n\n"
        self._preamble = [
            r"\usepackage[english]{babel}",
            r"\usepackage[letterpaper,top=2cm,bottom=2cm,left=3cm,right=3cm,marginparwidth=1.75cm]{geometry}",
            r"\usepackage{amsmath}",
            r"\usepackage{graphicx}",
            r"\usepackage[colorlinks=true, allcolors=blue]{hyperref}",
        ]
        self._doc_begin = "\\begin{document}\n\n"
        self._body = []
        self._generated_by = ''.join([r"\vspace*{\fill}", "\n\n" 
                                      r"\textit{Generated By} \textbf{LaTeXWorkSheets}:",
                                      r"\href{https://github.com/keithallatt/LaTeXWorkSheets}{GitHub Repo}"])
        self._doc_end = "\n\n\\end{document}"

    def add_content(self, tex):
        self._body.append(tex)

    def add_package(self, package, *options):
        self._preamble.append(fr"\usepackage[{', '.join(map(str, options))}]" + "{" + str(package) + "}")

    def __str__(self, solved=False):
        return "\n\n".join([
            self._doc_class,
            "\n".join(self._preamble),
            self._doc_begin,
            "\n\n".join(map(lambda x: x.__str__(solved) if isinstance(x, LaTeXPiece) else str(x), self._body)),
            self._generated_by,
            self._doc_end
        ])


def compile_tex(filename, tex, solutions=True, double_compile=False):
    """ Compile LaTeX code into a pdf and save it to the current working directory. """
    # get cwd to reset directory after.
    current = os.getcwd()
    # convert tex into a string, if not already a string.
    tex_content = tex.__str__(solutions) if isinstance(tex, LaTeXPiece) else str(tex)
    # create temp folder to compile in.
    temp_path = tempfile.mkdtemp()
    # change directory to temp folder.
    os.chdir(temp_path)

    # temporary document name, only having it saved here increases maintainability.
    doc_name = "document.tex"

    # write the LaTeX content to file
    with open(doc_name, 'w') as f:
        f.write(tex_content)

    # compile the document using pdflatex
    proc = subprocess.Popen(['pdflatex', '\\input{'+doc_name+'}'])
    proc.communicate()
    if double_compile:
        # for some applications, such as those that have tables of contents, sometimes 2 compiles are necessary.
        proc = subprocess.Popen(['pdflatex', '\\input{'+doc_name+'}'])
        proc.communicate()

    # rename the file to the specified name.
    os.rename(doc_name[:-3]+'pdf', filename)
    # copy the file back to the current
    shutil.copy(filename, current)
    # remove the temporary path
    shutil.rmtree(temp_path)
    # change the directory back.
    os.chdir(current)
